### ISSUE TITLE
图标的旋转角度不对

### ISSUE THREAD

**Issue by YokyAndKen** [weijun-lab/Leaflet.TrackPlayer#12]
<img width="187" alt="1725260759047" src="https://github.com/user-attachments/assets/efda9dd1-c40a-480d-8295-5d2fa7b98bbb">

绘制的时候发现图标的旋转角度跟路线对不上，请问这个是什么问题呢
    let track = new L.TrackPlayer([
      [25.10000, 120.30000], [26.50000, 120.70000], 
      [25.90000, 121.60000], [25.10000, 120.30000],
    ], {
      markerIcon: L.icon({
        iconUrl: `./iconfont/car.png`,
        iconSize: [40,40],
      }),
      speed: 120000, weight: 8, panTo: true, 
      markerRotation: true, rotationOrigin: "center", markerRotationOffset: 0
    }).addTo(this._mapContainer);
    track.start();

**Comment by YokyAndKen** [comment]
![Uploading 1725260759047.png…]()

**Comment by a864614973** [comment]
我也存在这个问题
![image](https://github.com/user-attachments/assets/bf50c4c0-078a-4c4d-b474-43ec6a341845)

**Comment by Axin3344** [comment]
通过下载使用作者的源代码解决了我的旋转角度问题，希望对你有所帮助
![Snipaste_2024-12-05_17-31-07](https://github.com/user-attachments/assets/e815362d-4c43-42ce-9ca9-3a4f35c24be5)

**Comment by Axin3344** [comment]
> 通过下载使用作者的源代码解决了我的旋转角度问题，希望对你有所帮助 ![Snipaste_2024-12-05_17-31-07](https://private-user-images.githubusercontent.com/114270904/392749466-e815362d-4c43-42ce-9ca9-3a4f35c24be5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTE0NDIsIm5iZiI6MTczMzM5MTE0MiwicGF0aCI6Ii8xMTQyNzA5MDQvMzkyNzQ5NDY2LWU4MTUzNjJkLTRjNDMtNDJjZS05Y2E5LTNhNGYzNWMyNGJlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTMyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODYwZTliOGY5ZWIwODkxMDI2MDMxMmQyYWM4ZjFjZjdjYjhmMTg3YmEyZGJkZTkxZGE1ZDk2ZTNkZDQwYjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LGMH8h371cSdM7STDVG6EzsThrpdnG4Urh51Hj3IEdM)

注意安装这几个包
![Snipaste_2024-12-05_17-33-31](https://github.com/user-attachments/assets/a399bb71-652e-4e24-b400-1c3a6740c76b)

**Comment by weijun-lab** [comment]
@YokyAndKen 问题已经解决了，再试试吧
