### ISSUE TITLE
trackIndex 为什么一直会是 0

### ISSUE THREAD

**Issue by dl1121** [weijun-lab/Leaflet.TrackPlayer#15]

**Comment by sofeking2020** [comment]
我也遇到这个问题，trackIndex一直是0
![bug](https://github.com/user-attachments/assets/e80be268-5e3e-4b5b-b924-62a9645cec1d)

**Comment by jxh-0514** [comment]
我使用的x,y坐标系，也遇到了这个问题，而且播放的时候起始位置变到左下角了
