### ISSUE TITLE
传入简单的平面坐标系数据后播放异常

### ISSUE THREAD

**Issue by jxh-0514** [weijun-lab/Leaflet.TrackPlayer#16]
leaflet地图坐标系为L.CRS.simple
轨迹数据
`[
    {
        "lat": 410,
        "lng": 1172
    },
    {
        "lat": 410,
        "lng": 1172
    },
    {
        "lat": 398,
        "lng": 1100
    },
    {
        "lat": 632,
        "lng": 1128
    },
    {
        "lat": 618,
        "lng": 1282
    },
    {
        "lat": 574,
        "lng": 1436
    },
    {
        "lat": 570,
        "lng": 1514
    },
    {
        "lat": 570,
        "lng": 1514
    },
    {
        "lat": 574,
        "lng": 1436
    },
    {
        "lat": 618,
        "lng": 1282
    },
    {
        "lat": 632,
        "lng": 1128
    },
    {
        "lat": 398,
        "lng": 1100
    },
    {
        "lat": 410,
        "lng": 1172
    },
    {
        "lat": 410,
        "lng": 1172
    },
    {
        "lat": 410,
        "lng": 1172
    },
    {
        "lat": 410,
        "lng": 1172
    },
    {
        "lat": 410,
        "lng": 1172
    },
    {
        "lat": 410,
        "lng": 1172
    },
    {
        "lat": 410,
        "lng": 1172
    },
    {
        "lat": 410,
        "lng": 1172
    }
]`
还未开始播放时的轨迹线
![image](https://github.com/user-attachments/assets/f2bc11d5-534b-4ec2-b415-2d4503658796)
执行播放后的轨迹线
![image](https://github.com/user-attachments/assets/e5b99939-bc14-44bb-a2d2-e7cf54238078)

**Comment by weijun-lab** [comment]
先转换成经纬度坐标再用吧，不支持L.CRS.simple坐标系&nbsp;


tian威君&amp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月15日(星期五) 晚上11:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [weijun-lab/Leaflet.TrackPlayer] 传入简单的平面坐标系数据后播放异常 (Issue #16)














 
leaflet地图坐标系为L.CRS.simple
 轨迹数据
 [ { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 398, "lng": 1100 }, { "lat": 632, "lng": 1128 }, { "lat": 618, "lng": 1282 }, { "lat": 574, "lng": 1436 }, { "lat": 570, "lng": 1514 }, { "lat": 570, "lng": 1514 }, { "lat": 574, "lng": 1436 }, { "lat": 618, "lng": 1282 }, { "lat": 632, "lng": 1128 }, { "lat": 398, "lng": 1100 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 } ]
 还未开始播放时的轨迹线
 image.png (view on web)
 执行播放后的轨迹线
 image.png (view on web)

**Comment by jxh-0514** [comment]
> 先转换成经纬度坐标再用吧，不支持L.CRS.simple坐标系&nbsp; tian威君&amp; ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年11月15日(星期五) 晚上11:18 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [weijun-lab/Leaflet.TrackPlayer] 传入简单的平面坐标系数据后播放异常 (Issue #16) leaflet地图坐标系为L.CRS.simple 轨迹数据 [ { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 398, "lng": 1100 }, { "lat": 632, "lng": 1128 }, { "lat": 618, "lng": 1282 }, { "lat": 574, "lng": 1436 }, { "lat": 570, "lng": 1514 }, { "lat": 570, "lng": 1514 }, { "lat": 574, "lng": 1436 }, { "lat": 618, "lng": 1282 }, { "lat": 632, "lng": 1128 }, { "lat": 398, "lng": 1100 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 }, { "lat": 410, "lng": 1172 } ] 还未开始播放时的轨迹线 image.png (view on web) 执行播放后的轨迹线 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

好的
