### ISSUE TITLE
有的轨迹数据，车里移动会错乱，有的正常，不明白什么情况

### ISSUE THREAD

**Issue by MKQueen** [weijun-lab/Leaflet.TrackPlayer#6]
<img width="669" alt="企业微信20240509-090804@2x" src="https://github.com/weijun-lab/Leaflet.TrackPlayer/assets/30900298/8af993da-fb06-4271-bac3-e0d219ad8be2">

**Comment by MKQueen** [comment]
<img width="716" alt="企业微信20240509-091051@2x" src="https://github.com/weijun-lab/Leaflet.TrackPlayer/assets/30900298/a56536ab-d28e-447a-b049-8b431a996437">
配置代码，我自己在geojson.io画的轨迹数据没什么问题，然后用真实数据，会有这种情况，有的真实数据原本正常，但是我处理纠偏，漂移点后也不正常了

**Comment by MKQueen** [comment]
[map.json](https://github.com/weijun-lab/Leaflet.TrackPlayer/files/15256390/map.json)
这是我处理过后的的真实数据

**Comment by weijun-lab** [comment]
我看看

**Comment by weijun-lab** [comment]
发生bug时，播放进度大概是多少，我定位下问题修复

**Comment by MKQueen** [comment]
> 发生bug时，播放进度大概是多少，我定位下问题修复

一播就出问题了

**Comment by weijun-lab** [comment]
我这边测试一切正常，确认下你的插件版本是不是2.0.2

**Comment by weijun-lab** [comment]
![image](https://github.com/weijun-lab/Leaflet.TrackPlayer/assets/55946457/4d12627b-bd7a-4e64-9b97-ee905e92e495)

**Comment by a864614973** [comment]
您好，我也是同样的问题，插件版本2.0.2
[result.csv](https://github.com/user-attachments/files/16884900/result.csv)
yi'xx文件是我的经纬度

**Comment by weijun-lab** [comment]
问题已经解决了，再试试吧
